#ifndef SHADOW_OF_FIRE_GAMECLOCK_H
#define SHADOW_OF_FIRE_GAMECLOCK_H

#define SECOND_IN_MILLISECONDS 1000.0f
#define FPS 60
#define FRAME_TIME_MILLISECONDS FPS / SECOND_IN_MILLISECONDS
#define MAX_DELTA_TIME_MILLISECONDS 0.05f

#endif //SHADOW_OF_FIRE_GAMECLOCK_H
